<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CantonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cantones = [

            ['canton' => 'Cuenca', 'id_provincia' => 1],
            ['canton' => 'Girón', 'id_provincia' => 1],
            ['canton' => 'Gualaceo', 'id_provincia' => 1],
            ['canton' => 'Nabón', 'id_provincia' => 1],
            ['canton' => 'Paute', 'id_provincia' => 1],
            ['canton' => 'Pucara', 'id_provincia' => 1],
            ['canton' => 'San Fernando', 'id_provincia' => 1],
            ['canton' => 'Santa Isabel', 'id_provincia' => 1],
            ['canton' => 'Sigsig', 'id_provincia' => 1],
            ['canton' => 'Oña', 'id_provincia' => 1],
            ['canton' => 'Chordeleg', 'id_provincia' => 1],
            ['canton' => 'El Pan', 'id_provincia' => 1],
            ['canton' => 'Sevilla de Oro', 'id_provincia' => 1],
            ['canton' => 'Guachapala', 'id_provincia' => 1],
            ['canton' => 'Camilo Ponce Enríquez', 'id_provincia' => 1],
            ['canton' => 'Guaranda', 'id_provincia' => 2],
            ['canton' => 'Chillanes', 'id_provincia' => 2],
            ['canton' => 'Chimbo', 'id_provincia' => 2],
            ['canton' => 'Echeandía', 'id_provincia' => 2],
            ['canton' => 'San Miguel', 'id_provincia' => 2],
            ['canton' => 'Caluma', 'id_provincia' => 2],
            ['canton' => 'Las Naves', 'id_provincia' => 2],
            ['canton' => 'Azogues', 'id_provincia' => 3],
            ['canton' => 'Biblián', 'id_provincia' => 3],
            ['canton' => 'Cañar', 'id_provincia' => 3],
            ['canton' => 'La Troncal', 'id_provincia' => 3],
            ['canton' => 'El Tambo', 'id_provincia' => 3],
            ['canton' => 'Déleg', 'id_provincia' => 3],
            ['canton' => 'Suscal', 'id_provincia' => 3],
            ['canton' => 'Tulcán', 'id_provincia' => 4],
            ['canton' => 'Bolívar', 'id_provincia' => 4],
            ['canton' => 'Espejo', 'id_provincia' => 4],
            ['canton' => 'Mira', 'id_provincia' => 4],
            ['canton' => 'Montúfar', 'id_provincia' => 4],
            ['canton' => 'San Pedro de Huaca', 'id_provincia' => 4],
            ['canton' => 'Latacunga', 'id_provincia' => 5],
            ['canton' => 'La Maná', 'id_provincia' => 5],
            ['canton' => 'Pangua', 'id_provincia' => 5],
            ['canton' => 'Pujili', 'id_provincia' => 5],
            ['canton' => 'Salcedo', 'id_provincia' => 5],
            ['canton' => 'Saquisilí', 'id_provincia' => 5],
            ['canton' => 'Sigchos', 'id_provincia' => 5],
            ['canton' => 'Riobamba', 'id_provincia' => 6],
            ['canton' => 'Alausi', 'id_provincia' => 6],
            ['canton' => 'Colta', 'id_provincia' => 6],
            ['canton' => 'Chambo', 'id_provincia' => 6],
            ['canton' => 'Chunchi', 'id_provincia' => 6],
            ['canton' => 'Guamote', 'id_provincia' => 6],
            ['canton' => 'Guano', 'id_provincia' => 6],
            ['canton' => 'Pallatanga', 'id_provincia' => 6],
            ['canton' => 'Penipe', 'id_provincia' => 6],
            ['canton' => 'Cumandá', 'id_provincia' => 6],
            ['canton' => 'Machala', 'id_provincia' => 7],
            ['canton' => 'Arenillas', 'id_provincia' => 7],
            ['canton' => 'Atahualpa', 'id_provincia' => 7],
            ['canton' => 'Balsas', 'id_provincia' => 7],
            ['canton' => 'Chilla', 'id_provincia' => 7],
            ['canton' => 'El Guabo', 'id_provincia' => 7],
            ['canton' => 'Huaquillas', 'id_provincia' => 7],
            ['canton' => 'Marcabelí', 'id_provincia' => 7],
            ['canton' => 'Pasaje', 'id_provincia' => 7],
            ['canton' => 'Piñas', 'id_provincia' => 7],
            ['canton' => 'Portovelo', 'id_provincia' => 7],
            ['canton' => 'Santa Rosa', 'id_provincia' => 7],
            ['canton' => 'Zaruma', 'id_provincia' => 7],
            ['canton' => 'Las Lajas', 'id_provincia' => 7],
            ['canton' => 'Esmeraldas', 'id_provincia' => 8],
            ['canton' => 'Eloy Alfaro', 'id_provincia' => 8],
            ['canton' => 'Muisne', 'id_provincia' => 8],
            ['canton' => 'Quinindé', 'id_provincia' => 8],
            ['canton' => 'San Lorenzo', 'id_provincia' => 8],
            ['canton' => 'Atacames', 'id_provincia' => 8],
            ['canton' => 'Rioverde', 'id_provincia' => 8],
            ['canton' => 'La Concordia', 'id_provincia' => 8],
            ['canton' => 'Guayaquil', 'id_provincia' => 9],
            ['canton' => 'Alfredo Baquerizo Moreno (Juján)', 'id_provincia' => 9],
            ['canton' => 'Balao', 'id_provincia' => 9],
            ['canton' => 'Balzar', 'id_provincia' => 9],
            ['canton' => 'Colimes', 'id_provincia' => 9],
            ['canton' => 'Daule', 'id_provincia' => 9],
            ['canton' => 'Durán', 'id_provincia' => 9],
            ['canton' => 'El Empalme', 'id_provincia' => 9],
            ['canton' => 'El Triunfo', 'id_provincia' => 9],
            ['canton' => 'Milagro', 'id_provincia' => 9],
            ['canton' => 'Naranjal', 'id_provincia' => 9],
            ['canton' => 'Naranjito', 'id_provincia' => 9],
            ['canton' => 'Palestina', 'id_provincia' => 9],
            ['canton' => 'Pedro Carbo', 'id_provincia' => 9],
            ['canton' => 'Samborondón', 'id_provincia' => 9],
            ['canton' => 'Santa Lucía', 'id_provincia' => 9],
            ['canton' => 'Salitre (Urbina Jado)', 'id_provincia' => 9],
            ['canton' => 'San Jacinto de Yaguachi', 'id_provincia' => 9],
            ['canton' => 'Playas', 'id_provincia' => 9],
            ['canton' => 'Simón Bolívar', 'id_provincia' => 9],
            ['canton' => 'Coronel Marcelino Maridueña', 'id_provincia' => 9],
            ['canton' => 'Lomas de Sargentillo', 'id_provincia' => 9],
            ['canton' => 'Nobol', 'id_provincia' => 9],
            ['canton' => 'General Antonio Elizalde', 'id_provincia' => 9],
            ['canton' => 'Isidro Ayora', 'id_provincia' => 9],
            ['canton' => 'Ibarra', 'id_provincia' => 10],
            ['canton' => 'Antonio Ante', 'id_provincia' => 10],
            ['canton' => 'Cotacachi', 'id_provincia' => 10],
            ['canton' => 'Otavalo', 'id_provincia' => 10],
            ['canton' => 'Pimampiro', 'id_provincia' => 10],
            ['canton' => 'San Miguel de Urcuquí', 'id_provincia' => 10],
            ['canton' => 'Loja', 'id_provincia' => 11],
            ['canton' => 'Calvas', 'id_provincia' => 11],
            ['canton' => 'Catamayo', 'id_provincia' => 11],
            ['canton' => 'Celica', 'id_provincia' => 11],
            ['canton' => 'Chaguarpamba', 'id_provincia' => 11],
            ['canton' => 'Espíndola', 'id_provincia' => 11],
            ['canton' => 'Gonzanamá', 'id_provincia' => 11],
            ['canton' => 'Macará', 'id_provincia' => 11],
            ['canton' => 'Paltas', 'id_provincia' => 11],
            ['canton' => 'Puyango', 'id_provincia' => 11],
            ['canton' => 'Saraguro', 'id_provincia' => 11],
            ['canton' => 'Sozoranga', 'id_provincia' => 11],
            ['canton' => 'Zapotillo', 'id_provincia' => 11],
            ['canton' => 'Pindal', 'id_provincia' => 11],
            ['canton' => 'Quilanga', 'id_provincia' => 11],
            ['canton' => 'Olmedo', 'id_provincia' => 11],
            ['canton' => 'Babahoyo', 'id_provincia' => 12],
            ['canton' => 'Baba', 'id_provincia' => 12],
            ['canton' => 'Montalvo', 'id_provincia' => 12],
            ['canton' => 'Puebloviejo', 'id_provincia' => 12],
            ['canton' => 'Quevedo', 'id_provincia' => 12],
            ['canton' => 'Urdaneta', 'id_provincia' => 12],
            ['canton' => 'Ventanas', 'id_provincia' => 12],
            ['canton' => 'Vínces', 'id_provincia' => 12],
            ['canton' => 'Palenque', 'id_provincia' => 12],
            ['canton' => 'Buena Fé', 'id_provincia' => 12],
            ['canton' => 'Valencia', 'id_provincia' => 12],
            ['canton' => 'Mocache', 'id_provincia' => 12],
            ['canton' => 'Quinsaloma', 'id_provincia' => 12],
            ['canton' => 'Portoviejo', 'id_provincia' => 13],
            ['canton' => 'Bolívar', 'id_provincia' => 13],
            ['canton' => 'Chone', 'id_provincia' => 13],
            ['canton' => 'El Carmen', 'id_provincia' => 13],
            ['canton' => 'Flavio Alfaro', 'id_provincia' => 13],
            ['canton' => 'Jipijapa', 'id_provincia' => 13],
            ['canton' => 'Junín', 'id_provincia' => 13],
            ['canton' => 'Manta', 'id_provincia' => 13],
            ['canton' => 'Montecristi', 'id_provincia' => 13],
            ['canton' => 'Paján', 'id_provincia' => 13],
            ['canton' => 'Pichincha', 'id_provincia' => 13],
            ['canton' => 'Rocafuerte', 'id_provincia' => 13],
            ['canton' => 'Santa Ana', 'id_provincia' => 13],
            ['canton' => 'Sucre', 'id_provincia' => 13],
            ['canton' => 'Tosagua', 'id_provincia' => 13],
            ['canton' => '24 de Mayo', 'id_provincia' => 13],
            ['canton' => 'Pedernales', 'id_provincia' => 13],
            ['canton' => 'Olmedo', 'id_provincia' => 13],
            ['canton' => 'Puerto López', 'id_provincia' => 13],
            ['canton' => 'Jama', 'id_provincia' => 13],
            ['canton' => 'Jaramijó', 'id_provincia' => 13],
            ['canton' => 'San Vicente', 'id_provincia' => 13],
            ['canton' => 'Morona', 'id_provincia' => 14],
            ['canton' => 'Gualaquiza', 'id_provincia' => 14],
            ['canton' => 'Limón Indanza', 'id_provincia' => 14],
            ['canton' => 'Palora', 'id_provincia' => 14],
            ['canton' => 'Santiago', 'id_provincia' => 14],
            ['canton' => 'Sucúa', 'id_provincia' => 14],
            ['canton' => 'Huamboya', 'id_provincia' => 14],
            ['canton' => 'San Juan Bosco', 'id_provincia' => 14],
            ['canton' => 'Taisha', 'id_provincia' => 14],
            ['canton' => 'Logroño', 'id_provincia' => 14],
            ['canton' => 'Pablo Sexto', 'id_provincia' => 14],
            ['canton' => 'Tiwintza', 'id_provincia' => 14],
            ['canton' => 'Tena', 'id_provincia' => 15],
            ['canton' => 'Archidona', 'id_provincia' => 15],
            ['canton' => 'El Chaco', 'id_provincia' => 15],
            ['canton' => 'Quijos', 'id_provincia' => 15],
            ['canton' => 'Carlos Julio Arosemena Tola', 'id_provincia' => 15],
            ['canton' => 'Pastaza', 'id_provincia' => 16],
            ['canton' => 'Mera', 'id_provincia' => 16],
            ['canton' => 'Santa Clara', 'id_provincia' => 16],
            ['canton' => 'Arajuno', 'id_provincia' => 16],
            ['canton' => 'Quito', 'id_provincia' => 17],
            ['canton' => 'Cayambe', 'id_provincia' => 17],
            ['canton' => 'Mejia', 'id_provincia' => 17],
            ['canton' => 'Pedro Moncayo', 'id_provincia' => 17],
            ['canton' => 'Rumiñahui', 'id_provincia' => 17],
            ['canton' => 'San Miguel de Los Bancos', 'id_provincia' => 17],
            ['canton' => 'Pedro Vicente Maldonado', 'id_provincia' => 17],
            ['canton' => 'Puerto Quito', 'id_provincia' => 17],
            ['canton' => 'Ambato', 'id_provincia' => 18],
            ['canton' => 'Baños de Agua Santa', 'id_provincia' => 18],
            ['canton' => 'Cevallos', 'id_provincia' => 18],
            ['canton' => 'Mocha', 'id_provincia' => 18],
            ['canton' => 'Patate', 'id_provincia' => 18],
            ['canton' => 'Quero', 'id_provincia' => 18],
            ['canton' => 'San Pedro de Pelileo', 'id_provincia' => 18],
            ['canton' => 'Santiago de Píllaro', 'id_provincia' => 18],
            ['canton' => 'Tisaleo', 'id_provincia' => 18],
            ['canton' => 'Zamora', 'id_provincia' => 19],
            ['canton' => 'Chinchipe', 'id_provincia' => 19],
            ['canton' => 'Nangaritza', 'id_provincia' => 19],
            ['canton' => 'Yacuambi', 'id_provincia' => 19],
            ['canton' => 'Yantzaza (Yanzatza)', 'id_provincia' => 19],
            ['canton' => 'El Pangui', 'id_provincia' => 19],
            ['canton' => 'Centinela del Cóndor', 'id_provincia' => 19],
            ['canton' => 'Palanda', 'id_provincia' => 19],
            ['canton' => 'Paquisha', 'id_provincia' => 19],
            ['canton' => 'San Cristóbal', 'id_provincia' => 20],
            ['canton' => 'Isabela', 'id_provincia' => 20],
            ['canton' => 'Santa Cruz', 'id_provincia' => 20],
            ['canton' => 'Lago Agrio', 'id_provincia' => 21],
            ['canton' => 'Gonzalo Pizarro', 'id_provincia' => 21],
            ['canton' => 'Putumayo', 'id_provincia' => 21],
            ['canton' => 'Shushufindi', 'id_provincia' => 21],
            ['canton' => 'Sucumbíos', 'id_provincia' => 21],
            ['canton' => 'Cascales', 'id_provincia' => 21],
            ['canton' => 'Cuyabeno', 'id_provincia' => 21],
            ['canton' => 'Orellana', 'id_provincia' => 22],
            ['canton' => 'Aguarico', 'id_provincia' => 22],
            ['canton' => 'La Joya de Los Sachas', 'id_provincia' => 22],
            ['canton' => 'Loreto', 'id_provincia' => 22],
            ['canton' => 'Santo Domingo', 'id_provincia' => 23],
            ['canton' => 'Santa Elena', 'id_provincia' => 24],
            ['canton' => 'La Libertad', 'id_provincia' => 24],
            ['canton' => 'Salinas', 'id_provincia' => 24],
            ['canton' => 'Las Golondrinas', 'id_provincia' => 25],
            ['canton' => 'Manga del Cura', 'id_provincia' => 25],
            ['canton' => 'El Piedrero', 'id_provincia' => 25],
        ];
        DB::table('canton')->insert($cantones);
    }
}
