<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParroquiaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parroquias = [

            ['parroquia' => 'Bellavista', 'id_canton' => 1],
            ['parroquia' => 'Cañaribamba', 'id_canton' => 1],
            ['parroquia' => 'El Batán', 'id_canton' => 1],
            ['parroquia' => 'El Sagrario', 'id_canton' => 1],
            ['parroquia' => 'El Vecino', 'id_canton' => 1],
            ['parroquia' => 'Gil Ramírez Dávalos', 'id_canton' => 1],
            ['parroquia' => 'Huaynacápac', 'id_canton' => 1],
            ['parroquia' => 'Machángara', 'id_canton' => 1],
            ['parroquia' => 'Monay', 'id_canton' => 1],
            ['parroquia' => 'San Blas', 'id_canton' => 1],
            ['parroquia' => 'San Sebastián', 'id_canton' => 1],
            ['parroquia' => 'Sucre', 'id_canton' => 1],
            ['parroquia' => 'Totoracocha', 'id_canton' => 1],
            ['parroquia' => 'Yanuncay', 'id_canton' => 1],
            ['parroquia' => 'Hermano Miguel', 'id_canton' => 1],
            ['parroquia' => 'Cuenca', 'id_canton' => 1],
            ['parroquia' => 'Baños', 'id_canton' => 1],
            ['parroquia' => 'Cumbe', 'id_canton' => 1],
            ['parroquia' => 'Chaucha', 'id_canton' => 1],
            ['parroquia' => 'Checa (Jidcay)', 'id_canton' => 1],
            ['parroquia' => 'Chiquintad', 'id_canton' => 1],
            ['parroquia' => 'Llacao', 'id_canton' => 1],
            ['parroquia' => 'Molleturo', 'id_canton' => 1],
            ['parroquia' => 'Nulti', 'id_canton' => 1],
            ['parroquia' => 'Octavio Cordero Palacios (Santa Rosa)', 'id_canton' => 1],
            ['parroquia' => 'Paccha', 'id_canton' => 1],
            ['parroquia' => 'Quingeo', 'id_canton' => 1],
            ['parroquia' => 'Ricaurte', 'id_canton' => 1],
            ['parroquia' => 'San Joaquín', 'id_canton' => 1],
            ['parroquia' => 'Santa Ana', 'id_canton' => 1],
            ['parroquia' => 'Sayausí', 'id_canton' => 1],
            ['parroquia' => 'Sidcay', 'id_canton' => 1],
            ['parroquia' => 'Sinincay', 'id_canton' => 1],
            ['parroquia' => 'Tarqui', 'id_canton' => 1],
            ['parroquia' => 'Turi', 'id_canton' => 1],
            ['parroquia' => 'Valle', 'id_canton' => 1],
            ['parroquia' => 'Victoria del Portete (Irquis)', 'id_canton' => 1],
            ['parroquia' => 'Girón', 'id_canton' => 2],
            ['parroquia' => 'Asunción', 'id_canton' => 2],
            ['parroquia' => 'San Gerardo', 'id_canton' => 2],
            ['parroquia' => 'Gualaceo', 'id_canton' => 3],
            ['parroquia' => 'Chordeleg', 'id_canton' => 3],
            ['parroquia' => 'Daniel Córdova Toral (El Oriente)', 'id_canton' => 3],
            ['parroquia' => 'Jadán', 'id_canton' => 3],
            ['parroquia' => 'Mariano Moreno', 'id_canton' => 3],
            ['parroquia' => 'Principal', 'id_canton' => 3],
            ['parroquia' => 'Remigio Crespo Toral (Gúlag)', 'id_canton' => 3],
            ['parroquia' => 'San Juan', 'id_canton' => 3],
            ['parroquia' => 'Zhidmad', 'id_canton' => 3],
            ['parroquia' => 'Luis Cordero Vega', 'id_canton' => 3],
            ['parroquia' => 'Simón Bolívar (Cab En Gañanzol)', 'id_canton' => 3],
            ['parroquia' => 'Nabón', 'id_canton' => 4],
            ['parroquia' => 'Cochapata', 'id_canton' => 4],
            ['parroquia' => 'El Progreso (Cab.En Zhota)', 'id_canton' => 4],
            ['parroquia' => 'Las Nieves (Chaya)', 'id_canton' => 4],
            ['parroquia' => 'Oña', 'id_canton' => 4],
            ['parroquia' => 'Paute', 'id_canton' => 5],
            ['parroquia' => 'Amaluza', 'id_canton' => 5],
            ['parroquia' => 'Bulán (José Víctor Izquierdo)', 'id_canton' => 5],
            ['parroquia' => 'Chicán (Guillermo Ortega)', 'id_canton' => 5],
            ['parroquia' => 'El Cabo', 'id_canton' => 5],
            ['parroquia' => 'Guachapala', 'id_canton' => 5],
            ['parroquia' => 'Guarainag', 'id_canton' => 5],
            ['parroquia' => 'Palmas', 'id_canton' => 5],
            ['parroquia' => 'Pan', 'id_canton' => 5],
            ['parroquia' => 'San Cristóbal (Carlos Ordóñez Lazo)', 'id_canton' => 5],
            ['parroquia' => 'Sevilla de Oro', 'id_canton' => 5],
            ['parroquia' => 'Tomebamba', 'id_canton' => 5],
            ['parroquia' => 'Dug Dug', 'id_canton' => 5],
            ['parroquia' => 'Pucará', 'id_canton' => 6],
            ['parroquia' => 'Camilo Ponce Enríquez (Cab. En Río 7 de Mollepongo)', 'id_canton' => 6],
            ['parroquia' => 'San Rafael de Sharug', 'id_canton' => 6],
            ['parroquia' => 'San Fernando', 'id_canton' => 7],
            ['parroquia' => 'Chumblín', 'id_canton' => 7],
            ['parroquia' => 'Santa Isabel (Chaguarurco)', 'id_canton' => 8],
            ['parroquia' => 'Abdón Calderón (La Unión)', 'id_canton' => 8],
            ['parroquia' => 'El Carmen de Pijilí', 'id_canton' => 8],
            ['parroquia' => 'Zhaglli (Shaglli)', 'id_canton' => 8],
            ['parroquia' => 'San Salvador de Cañaribamba', 'id_canton' => 8],
            ['parroquia' => 'Sigsig', 'id_canton' => 9],
            ['parroquia' => 'Cuchil (Cutchil)', 'id_canton' => 9],
            ['parroquia' => 'Gima', 'id_canton' => 9],
            ['parroquia' => 'Guel', 'id_canton' => 9],
            ['parroquia' => 'Ludo', 'id_canton' => 9],
            ['parroquia' => 'San Bartolomé', 'id_canton' => 9],
            ['parroquia' => 'San José de Raranga', 'id_canton' => 9],
            ['parroquia' => 'San Felipe de Oña Cabecera Cantonal', 'id_canton' => 10],
            ['parroquia' => 'Susudel', 'id_canton' => 10],
            ['parroquia' => 'Chordeleg', 'id_canton' => 11],
            ['parroquia' => 'Principal', 'id_canton' => 11],
            ['parroquia' => 'La Unión', 'id_canton' => 11],
            ['parroquia' => 'Luis Galarza Orellana (Cab.En Delegsol)', 'id_canton' => 11],
            ['parroquia' => 'San Martín de Puzhio', 'id_canton' => 11],
            ['parroquia' => 'El Pan', 'id_canton' => 12],
            ['parroquia' => 'Amaluza', 'id_canton' => 12],
            ['parroquia' => 'Palmas', 'id_canton' => 12],
            ['parroquia' => 'San Vicente', 'id_canton' => 12],
            ['parroquia' => 'Sevilla de Oro', 'id_canton' => 13],
            ['parroquia' => 'Amaluza', 'id_canton' => 13],
            ['parroquia' => 'Palmas', 'id_canton' => 13],
            ['parroquia' => 'Guachapala', 'id_canton' => 14],
            ['parroquia' => 'Camilo Ponce Enríquez', 'id_canton' => 15],
            ['parroquia' => 'El Carmen de Pijilí', 'id_canton' => 15],
            ['parroquia' => 'Ángel Polibio Cháves', 'id_canton' => 16],
            ['parroquia' => 'Gabriel Ignacio Veintimilla', 'id_canton' => 16],
            ['parroquia' => 'Guanujo', 'id_canton' => 16],
            ['parroquia' => 'Guaranda', 'id_canton' => 16],
            ['parroquia' => 'Facundo Vela', 'id_canton' => 16],
            ['parroquia' => 'Guanujo', 'id_canton' => 16],
            ['parroquia' => 'Julio E. Moreno (Catanahuán Grande)', 'id_canton' => 16],
            ['parroquia' => 'Las Naves', 'id_canton' => 16],
            ['parroquia' => 'Salinas', 'id_canton' => 16],
            ['parroquia' => 'San Lorenzo', 'id_canton' => 16],
            ['parroquia' => 'San Simón (Yacoto)', 'id_canton' => 16],
            ['parroquia' => 'Santa Fé (Santa Fé)', 'id_canton' => 16],
            ['parroquia' => 'Simiátug', 'id_canton' => 16],
            ['parroquia' => 'San Luis de Pambil', 'id_canton' => 16],
            ['parroquia' => 'Chillanes', 'id_canton' => 17],
            ['parroquia' => 'San José del Tambo (Tambopamba)', 'id_canton' => 17],
            ['parroquia' => 'San José de Chimbo', 'id_canton' => 18],
            ['parroquia' => 'Asunción (Asancoto)', 'id_canton' => 18],
            ['parroquia' => 'Caluma', 'id_canton' => 18],
            ['parroquia' => 'Magdalena (Chapacoto)', 'id_canton' => 18],
            ['parroquia' => 'San Sebastián', 'id_canton' => 18],
            ['parroquia' => 'Telimbela', 'id_canton' => 18],
            ['parroquia' => 'Echeandía', 'id_canton' => 19],
            ['parroquia' => 'San Miguel', 'id_canton' => 20],
            ['parroquia' => 'Balsapamba', 'id_canton' => 20],
            ['parroquia' => 'Bilován', 'id_canton' => 20],
            ['parroquia' => 'Régulo de Mora', 'id_canton' => 20],
            ['parroquia' => 'San Pablo (San Pablo de Atenas)', 'id_canton' => 20],
            ['parroquia' => 'Santiago', 'id_canton' => 20],
            ['parroquia' => 'San Vicente', 'id_canton' => 20],
            ['parroquia' => 'Caluma', 'id_canton' => 21],
            ['parroquia' => 'Las Mercedes', 'id_canton' => 22],
            ['parroquia' => 'Las Naves', 'id_canton' => 22],
            ['parroquia' => 'Las Naves', 'id_canton' => 22],
            ['parroquia' => 'Aurelio Bayas Martínez', 'id_canton' => 23],
            ['parroquia' => 'Azogues', 'id_canton' => 23],
            ['parroquia' => 'Borrero', 'id_canton' => 23],
            ['parroquia' => 'San Francisco', 'id_canton' => 23],
            ['parroquia' => 'Azogues', 'id_canton' => 23],
            ['parroquia' => 'Cojitambo', 'id_canton' => 23],
            ['parroquia' => 'Déleg', 'id_canton' => 23],
            ['parroquia' => 'Guapán', 'id_canton' => 23],
            ['parroquia' => 'Javier Loyola (Chuquipata)', 'id_canton' => 23],
            ['parroquia' => 'Luis Cordero', 'id_canton' => 23],
            ['parroquia' => 'Pindilig', 'id_canton' => 23],
            ['parroquia' => 'Rivera', 'id_canton' => 23],
            ['parroquia' => 'San Miguel', 'id_canton' => 23],
            ['parroquia' => 'Solano', 'id_canton' => 23],
            ['parroquia' => 'Taday', 'id_canton' => 23],
            ['parroquia' => 'Biblián', 'id_canton' => 24],
            ['parroquia' => 'Nazón (Cab. En Pampa de Domínguez)', 'id_canton' => 24],
            ['parroquia' => 'San Francisco de Sageo', 'id_canton' => 24],
            ['parroquia' => 'Turupamba', 'id_canton' => 24],
            ['parroquia' => 'Jerusalén', 'id_canton' => 24],
            ['parroquia' => 'Cañar', 'id_canton' => 25],
            ['parroquia' => 'Chontamarca', 'id_canton' => 25],
            ['parroquia' => 'Chorocopte', 'id_canton' => 25],
            ['parroquia' => 'General Morales', 'id_canton' => 25],
            ['parroquia' => 'Gualleturo', 'id_canton' => 25],
            ['parroquia' => 'Honorato Vásquez (San Marcos)', 'id_canton' => 25],
            ['parroquia' => 'Ingapirca', 'id_canton' => 25],
            ['parroquia' => 'Juncal', 'id_canton' => 25],
            ['parroquia' => 'San Antonio', 'id_canton' => 25],
            ['parroquia' => 'Suscal', 'id_canton' => 25],
            ['parroquia' => 'Tambo', 'id_canton' => 26],
            ['parroquia' => 'El Retiro', 'id_canton' => 26],
            ['parroquia' => 'Pucará', 'id_canton' => 26],
            ['parroquia' => 'Zhud', 'id_canton' => 26],
            ['parroquia' => 'La Troncal', 'id_canton' => 27],
            ['parroquia' => 'Manuel J. Calle', 'id_canton' => 27],
            ['parroquia' => 'Pancho Negro', 'id_canton' => 27],
            ['parroquia' => 'Suscal', 'id_canton' => 27],
            ['parroquia' => 'Déleg', 'id_canton' => 28],
            ['parroquia' => 'Solano', 'id_canton' => 28],
            ['parroquia' => 'El Triunfo', 'id_canton' => 29],
            ['parroquia' => 'Chaguarpamba', 'id_canton' => 30],
            ['parroquia' => 'Buenavista', 'id_canton' => 30],
            ['parroquia' => 'Cazaderos', 'id_canton' => 30],
            ['parroquia' => 'Guarainag', 'id_canton' => 30],
            ['parroquia' => 'Paletillas', 'id_canton' => 30],
            ['parroquia' => 'Olmedo', 'id_canton' => 30],
            ['parroquia' => 'Alamores', 'id_canton' => 31],
            ['parroquia' => 'Amaluza', 'id_canton' => 31],
            ['parroquia' => 'Ciano', 'id_canton' => 31],
            ['parroquia' => 'El Limo (Sozoranga)', 'id_canton' => 31],
            ['parroquia' => 'Lucero', 'id_canton' => 31],
            ['parroquia' => 'San Antonio de las Aradas', 'id_canton' => 31],
            ['parroquia' => 'Sozoranga', 'id_canton' => 31],
            ['parroquia' => 'Zapotillo', 'id_canton' => 32],
            ['parroquia' => 'Bolaspamba', 'id_canton' => 32],
            ['parroquia' => 'Cazaderos', 'id_canton' => 32],
            ['parroquia' => 'Garzareal', 'id_canton' => 32],
            ['parroquia' => 'Limones', 'id_canton' => 32],
            ['parroquia' => 'Paletillas', 'id_canton' => 32],
            ['parroquia' => 'Puyango', 'id_canton' => 32],
            ['parroquia' => 'Celica', 'id_canton' => 33],
            ['parroquia' => 'Chaquiras', 'id_canton' => 33],
            ['parroquia' => 'Cruzpamba (Cab. En Y del Muerto)', 'id_canton' => 33],
            ['parroquia' => 'El Empalme', 'id_canton' => 33],
            ['parroquia' => 'General E. Ortega', 'id_canton' => 33],
            ['parroquia' => 'Honestino Ruiz (Progreso)', 'id_cantton' => 33],
            ['parroquia' => 'Sabanilla', 'id_canton' => 33],
            ['parroquia' => 'Tnte. Maximiliano Rodríguez Loaiza', 'id_canton' => 33],
            ['parroquia' => 'Pindal', 'id_canton' => 34],
            ['parroquia' => 'Milagros', 'id_canton' => 34],
            ['parroquia' => '12 de Diciembre', 'id_canton' => 34],
            ['parroquia' => 'Zumba', 'id_canton' => 35],
            ['parroquia' => 'Amaluza', 'id_canton' => 35],
            ['parroquia' => 'Bellavista', 'id_canton' => 35],
            ['parroquia' => 'Guayquichuma', 'id_canton' => 35],
            ['parroquia' => 'Jimbura', 'id_canton' => 35],
            ['parroquia' => 'Valladolid', 'id_canton' => 35],
            ['parroquia' => 'Palanda', 'id_canton' => 36],
            ['parroquia' => 'El Porvenir del Carmen', 'id_canton' => 36],
            ['parroquia' => 'San Francisco del Vergel', 'id_canton' => 36],
            ['parroquia' => 'Valladolid', 'id_canton' => 36],
            ['parroquia' => 'Yangana', 'id_canton' => 37],
            ['parroquia' => 'Quinara', 'id_canton' => 37],
            ['parroquia' => 'San Antonio de las Aradas', 'id_canton' => 37],
            ['parroquia' => 'Vilcabamba', 'id_canton' => 37],
            ['parroquia' => 'Loja', 'id_canton' => 37],
            ['parroquia' => 'Chantaco', 'id_canton' => 37],
            ['parroquia' => 'Chuquiribamba', 'id_canton' => 37],
            ['parroquia' => 'Gualel', 'id_canton' => 37],
            ['parroquia' => 'Jimbilla', 'id_canton' => 37],
            ['parroquia' => 'Malacatos (San Vicente Mártir)', 'id_canton' => 37],
            ['parroquia' => 'San Lucas', 'id_canton' => 37],
            ['parroquia' => 'Santiago', 'id_canton' => 37],
            ['parroquia' => 'Taquil (Miguel Lau)', 'id_canton' => 37],
            ['parroquia' => 'Vilcabamba', 'id_canton' => 37],
            ['parroquia' => 'Yangana', 'id_canton' => 37],
            ['parroquia' => 'El Cisne', 'id_canton' => 37],
            ['parroquia' => 'Amaluza', 'id_canton' => 37],
            ['parroquia' => 'San Pedro de Vilcabamba', 'id_canton' => 37],
            ['parroquia' => 'Gonzanamá', 'id_canton' => 38],
            ['parroquia' => 'Changaimina', 'id_canton' => 38],
            ['parroquia' => 'Eguiguren', 'id_canton' => 38],
            ['parroquia' => 'Guachanamá', 'id_canton' => 38],
            ['parroquia' => 'Quilanga', 'id_canton' => 38],
            ['parroquia' => 'Sacapalca', 'id_canton' => 38],
            ['parroquia' => 'Catamayo (La Toma)', 'id_canton' => 39],
            ['parroquia' => 'Guarainag', 'id_canton' => 39],
            ['parroquia' => 'San Pedro de la Bendita', 'id_canton' => 39],
            ['parroquia' => 'Zambi', 'id_canton' => 39],
            ['parroquia' => 'Malacatos', 'id_canton' => 39],
            ['parroquia' => 'Macará', 'id_canton' => 40],
            ['parroquia' => 'Larama', 'id_canton' => 40],
            ['parroquia' => 'Sabiango', 'id_canton' => 40],
            ['parroquia' => 'Vicente Anda Aguirre', 'id_canton' => 40],
            ['parroquia' => 'Sozoranga', 'id_canton' => 40],
            ['parroquia' => 'Paltas (Catacocha)', 'id_canton' => 41],
            ['parroquia' => 'Cariamanga', 'id_canton' => 41],
            ['parroquia' => 'Guachanamá', 'id_canton' => 41],
            ['parroquia' => 'Lauro Guerrero', 'id_canton' => 41],
            ['parroquia' => 'Olmedo', 'id_canton' => 41],
            ['parroquia' => 'San Antonio', 'id_canton' => 41],
            ['parroquia' => 'Yamana', 'id_canton' => 41],
            ['parroquia' => 'Zapotillo', 'id_canton' => 41],
            ['parroquia' => 'Puyango (Puyango)', 'id_canton' => 41],
            ['parroquia' => 'Quilanga', 'id_canton' => 41],
            ['parroquia' => 'Calvas (Cariamanga)', 'id_canton' => 42],
            ['parroquia' => 'Colaisaca', 'id_canton' => 42],
            ['parroquia' => 'El Lucero', 'id_canton' => 42],
            ['parroquia' => 'San Vicente', 'id_canton' => 42],
            ['parroquia' => 'Utuana', 'id_canton' => 42],
            ['parroquia' => 'Bellavista', 'id_canton' => 42],
            ['parroquia' => 'Sozoranga', 'id_canton' => 42],
            ['parroquia' => 'Espíndola (Amaluza)', 'id_canton' => 43],
            ['parroquia' => 'Amaluza', 'id_canton' => 43],
            ['parroquia' => 'Bellamaría', 'id_canton' => 43],
            ['parroquia' => 'Chantaco', 'id_canton' => 43],
            ['parroquia' => 'Jimbura', 'id_canton' => 43],
            ['parroquia' => 'Santa Teresita', 'id_canton' => 43],
            ['parroquia' => 'Zumba', 'id_canton' => 43],
            ['parroquia' => 'Chaguarpamba', 'id_canton' => 44],
            ['parroquia' => 'Buenavista', 'id_canton' => 44],
            ['parroquia' => 'Cazaderos', 'id_canton' => 44],
            ['parroquia' => 'Guarainag', 'id_canton' => 44],
            ['parroquia' => 'Olmedo', 'id_canton' => 44],
            ['parroquia' => 'Paletillas', 'id_canton' => 44],
            ['parroquia' => 'Puyango', 'id_canton' => 44],
            ['parroquia' => 'Quilanga', 'id_canton' => 44],
            ['parroquia' => 'Saraguro', 'id_canton' => 45],
            ['parroquia' => 'Celén', 'id_canton' => 45],
            ['parroquia' => 'Lluzhapa', 'id_canton' => 45],
            ['parroquia' => 'Manú', 'id_canton' => 45],
            ['parroquia' => 'San Antonio de Cumbe', 'id_canton' => 45],
            ['parroquia' => 'San Pablo de Tenta', 'id_canton' => 45],
            ['parroquia' => 'Selva Alegre', 'id_canton' => 45],
            ['parroquia' => 'Urdaneta (Paquishapa)', 'id_canton' => 45],
            ['parroquia' => 'Yacuambi (28 de Mayo)', 'id_canton' => 46],
            ['parroquia' => 'Guarainag', 'id_canton' => 46],
            ['parroquia' => 'La Paz', 'id_canton' => 46],
            ['parroquia' => 'San José de Yacuambi', 'id_canton' => 46],
            ['parroquia' => 'Tutupali', 'id_canton' => 46],
            ['parroquia' => 'Paquisha', 'id_canton' => 47],
            ['parroquia' => 'Bellavista', 'id_canton' => 47],
            ['parroquia' => 'El Pangui', 'id_canton' => 48],
            ['parroquia' => 'El Guismi', 'id_canton' => 48],
            ['parroquia' => 'Tundayme', 'id_canton' => 48],
            ['parroquia' => 'Yantzaza (Yanzatza)', 'id_canton' => 49],
            ['parroquia' => 'Chicaña', 'id_canton' => 49],
            ['parroquia' => 'Los Encuentros', 'id_canton' => 49],
            ['parroquia' => 'Zurmi', 'id_canton' => 49],
            ['parroquia' => 'Zamora', 'id_canton' => 50],
            ['parroquia' => 'Cumbaratza', 'id_canton' => 50],
            ['parroquia' => 'Guadalupe', 'id_canton' => 50],
            ['parroquia' => 'Imbana (La Libertad)', 'id_canton' => 50],
            ['parroquia' => 'Valladolid', 'id_canton' => 50],

        ];
    }
}
